### PR TITLE
Implemented float model

### PR DESCRIPTION
**Pull request by jirkavrba**
https://github.com/Hi-Folks/rando-php/issues/35

### CODE REVIEW

**Comment by roberto-butti** [comment]
Hi @jirkavrba  this PR is great!
High quality, and I see you wrote tests.
With this project I would like to aim 100% of test coverage. So thank you for that.

I have just a question: why _min_ and _max_ are defined as integers? Do you think is feasible to define them was float ?

I think that define min and max as float has a great impact on the code, and the logic on _generate()_. Is it corrrect?

**Comment by roberto-butti** [comment]
I. know that the usage of mt_rand has a kind of "warning":

> This function does not generate cryptographically secure values, and should not be used for cryptographic purposes

but what do you think if we could use something like that (it is just a snippet, probably there is room to improve it):

```
function randomFloat($min, $max) {
    return $min + mt_rand() / mt_getrandmax() * ($max - $min);
}

var_dump(randomFloat(2, 20));
var_dump(randomFloat(2.1, 2.2));
var_dump(randomFloat(-2.2, -1.55));
```

**Comment by jirkavrba** [comment]
Oh, I totally missed the option of min and max being a float, this usage makes a lot of sense.
I will have a look at it, the `mt_rand() / mt_getrandmax()` seems to have maximum of 10 decimals, which seems reasonable enough (with the average number of decimals being around ~7.2 according to the IEEE spec)

**Comment by jirkavrba** [comment]
Unfortunately, after several attempts, I am not able to come up with an efficient solution to generate random floats with given precision, should the `decimals` parameter be treated as a maximum precision or should I submit a little bit inefficient solution using string conversion?

**Comment by roberto-butti** [comment]
> Unfortunately, after several attempts, I am not able to come up with an efficient solution to generate random floats with given precision, should the `decimals` parameter be treated as a maximum precision or should I submit a little bit inefficient solution using string conversion?

Hi, decimal could be treated as max precision.

**Comment by jirkavrba** [comment]
Great, in that case, the implementation will be trivial and less error-prone

**Comment by jirkavrba** [comment]
I also added some additional test cases and the code coverage should be 100% now for floats
image

**Pull request merged**
