### PR TITLE
update char implementation

### PR DESCRIPTION
**Pull request by eruhaji**
This contains the new alpha method implementation, and the new alphaLower, alphaUpper methods.

### CODE REVIEW

**Comment by roberto-butti** [comment]
what do you think instad of alphaLower and alphaUpper, have 
alpha(), lower(), and upper(). lower and upper() are modifiers that indicates that the user wants just lower or upper case chars. (this is valid also if we have alphanumeric())

This could mean that in alpha(), alphanumeric() numeric() and lower and upper() we keep track what the user wants, via some flags for example
$this->alpha (boolean);
$this->numeric (boolean);
$this->lower (boolean),
$this->upper(boolean);

and just in generate we cuold generate the right array based on the above flags.
@xanaDev what do you think ?

**Comment by eruhaji** [comment]
You mean you want to be able to use it like so

alphanumeric lowercase char:
Randomize::char()->alpha()->numeric()->lower()->generate(); // 4, a, ...

alpha uppercase:
Randomize::char()->alpha()->upper()->generate(); // D, U, ...

I think we can achieve that without using any flags.

**Comment by roberto-butti** [comment]
@xanaDev  exactly.
Consider that i fixed 64 (array_merge VS +) so please update your master branch in order to avoid conflicts

**Comment by roberto-butti** [comment]
we could have also
Randomize::char()->alphanumeric()->lower()->generate(); 
that generates
a, b, c,...z, 1,2,...,0

**Pull request merged**
