### PR TITLE
feat : add char model

### PR DESCRIPTION
**Pull request by parnus01**
related #1

### CODE REVIEW

**Comment by roberto-butti** [comment]
I thing that instead of having $min and $max as attributes (useful for Integers), we could have $ascii_codes as attribute.
The default is to set asci_codes as you did: $this->ascii_codes = range(48, 57) + range(97, 122);
We could create new methods for example numeric() that set
```
$this->ascii_codes = range(48, 57);
```
We could create ew methods for example alpha() that set
```
$this->ascii_codes = range(97, 122);
```
We could create ew methods for example alphanumeric() that set
```
$this->ascii_codes = range(48, 57) + range(97, 122);
```

In the generate() method the random_int has parameters 0 and the lenght of the $this->ascii_codes ( -1 )

@parnus01 If you would like to complete, I can wait your changes. Else, it is fine aswell, i could merge into master and create a new specific issue with those suggestions. Let me know.
Thank you!!!
;)

**Comment by parnus01** [comment]
Already fix by your advice, but could you merge this PR after 1 Oct ( for festival milestone) .

**Comment by roberto-butti** [comment]
> Already fix by your advice, but could you merge this PR after 1 Oct ( for festival milestone) .

Thank you. As far as I know, for the Hacktoberfest the PR counts when you open a PR. It doens't matter if it is accepted or not.

**Comment by parnus01** [comment]
Really ?, so please merged it ? 😂

**Comment by parnus01** [comment]
Or you can close this PR ?

**Comment by roberto-butti** [comment]
> Or you can close this PR ?

Screenshot 2020-09-26 at 12 54 44

If you want that this PR coounts for hacktoberfest we could proceed in this way:
- I can delete this PR (cloose without merge)
- on 1st october you can re open the same Pull request.

This is my suggestion if you want to make your PR counts for hacktoberfest.
LEt me know, if you want to proceed in this way.
Because if i merge now, i think that this PR doesn't count for hacktoberfest.
I'm open to all possibilities ;)

**Comment by parnus01** [comment]
Understood please help to close without merge.

**Pull request closed without merging**
